### PR TITLE
[Bug] Propagate error callback when input param is provided

### LINKED ISSUE #37: I am trying to return an error but the error is not being propagated
While using a bimap with success and error callbacks and I try to use the error callback from within the task:

```
/* Action calling tasks */
export const loadFilesUpdater = (state, action) => {
  const {files} = action;

  const filesToLoad = files.map(fileBlob => processFileToLoad(fileBlob));

  // reader -> parser -> augment -> receiveVisData
  const loadFileTasks = [
    Task.all(filesToLoad.map(LOAD_FILE_TASK)).bimap(
      results => {
        const data = results.reduce((f, c) => ({
          // using concat here because the current datasets could be an array or a single item
          datasets: f.datasets.concat(c.datasets),
          // we need to deep merge this thing unless we find a better solution
          // this case will only happen if we allow to load multiple keplergl json files
          config: {
            ...f.config,
            ...(c.config || {})
          }
        }), {datasets: [], config: {}, options: {centerMap: true}});
        return loadFilesSuccess(data);
      },
      error => loadFilesErr(error)
    )
  ];

  return withTask(
    {
      ...state,
      visState: {
        ...state.visState,
        fileLoading: true
      }
    },
    loadFileTasks
  );
};
```

```
/* Load file Task */
export const LOAD_FILE_TASK = taskCreator(
  ({fileBlob, info, handler, processor}, success, error) =>
    handler(fileBlob, processor)
      .then(result => {
        !result ?
          error(new Error('Result is empty'))
          : result.datasets ?
            success(result)
            : success({datasets: {data: result, info}});
      })
      .catch(err => error(err)),
  'LOAD_FILE_TASK'
);
```
the bimap error callback is not being called.

But if i do the following
```
error(null)
```
the callback is being called correctly with null as paramenter.

I was digging around the react-palm code and i found out if I try to use the error callback with a non-null param the flow is being stopped here:
https://github.com/btford/react-palm/blob/06296ad9913e754f86db72caf0b90d0744d16f39/src/tasks/core.js#L362

### PR DESCRIPTION
**Pull request by macrigiuseppe**
This pull request fixes https://github.com/btford/react-palm/issues/37

### CODE REVIEW

File: src/tasks/core.js [hunk 1]
```diff
@@ -359,7 +359,7 @@ export function all<AllTasks: $ReadOnlyArray<Task<mixed, mixed>>>(
       }
 
       function anyError(err) {
-        if (err) {
+        if (!err) {
```
Comment (btford) [inline src/tasks/core.js:362]: I should add some tests around this.

**Review by btford — APPROVED** [review]
